language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
    - pip install pandas
    - pip install numpy
    - pip install xarray
    - pip install pytz
    - pip install netCDF4

script:
    - python tests/test.py
