package:
  name: jaws
  version: "0.2.1"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4
  run:
    - python
    - pandas
    - numpy
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4

about:
  home: https://github.com/jaws/jaws
  license: Apache License, Version 2.0
  license_file: LICENSE
