package:
  name: jaws
  version: "0.2.1"

source:
  path: ../source/

build:
  entry_points:
    - jaws = jaws:main
    - aaws2nc = aaws2nc:aaws2nc
    - common = common:write_data
    - gcnet2nc = gcnet2nc:gcnet2nc
    - promice2nc = promice2nc:promice2nc
    - sunposition = sunposition:main

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy
    - xarray
    - pytz
    - netcdf4
    - matplotlib
  run:
    - python
    - pandas
    - numpy
    - xarray
    - pytz
    - netcdf4
    - matplotlib

about:
  home: https://github.com/jaws/jaws
  license: Apache License, Version 2.0
  license_file: LICENSE
